# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoliathNationalBank' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GoliathNationalBank
  pod 'Alamofire', '~> 4.7'
  pod 'AlamofireObjectMapper', '~> 5.2'

  target 'GoliathNationalBankTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GoliathNationalBankUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
